name: Build Website

on: [push]

jobs:
  build-website:
    name: Build website
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: actions/checkout@v4

      - run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - run: wasm-pack build

      - name: Build the website with angular
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
      - run: npm install
      - run: tar -czf website.tar.gz *


      - name: Archive Website
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: website.tar.gz