name: Build Website

on: [push]

jobs:
  build-website:
    name: Build website
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build rust with wasm-pack
        run: |
          rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          wasm-pack build

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Publish wasm-pack generated node package to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd ./pkg
          npm publish --provenance --access public

      - name: Build website with npm
        run: | 
          npm install www
          tar -czf website.tar.gz ./www/*

      - name: Archive Website
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: ./website.tar.gz
