name: Build Website

on:
  push:
    branches:
      - main

jobs:
  wasm-to-npm:
    name: Publish wasm-pack generated package to npm
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    strategy:
      matrix:
        toolchain:
          - stable
    steps:
      - uses: actions/checkout@v4

      - name: Build rust with wasm-pack
        env:
          NPM_USER: ${{ secrets.NPM_USER }}
        run: |
          rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
          curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
          wasm-pack build --scope=$NPM_USER

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Publish wasm-pack generated node package to npm
        continue-on-error: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          cd ./pkg
          npm publish --access public

  archive-website:
    name: Build and archive website
    runs-on: ubuntu-latest
    needs: wasm-to-npm
    if: always()
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Build website with npm
        run: |
          cd www
          npm install
          npx webpack
          tar -czf website.tar.gz ./dist/*

      - name: Archive Website
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: ./www/website.tar.gz
